name: "$INSTALLNAME"
docker-storage-driver: overlay
docker-install-url: https://raw.githubusercontent.com/rancher/install-docker/master/17.09.0.sh
driver:
  name: azure
  private-ip-interface: eth0
  options:
    azure-client-id: "$AZURE_CLIENT_ID"
    azure-client-secret: "$AZURE_CLIENT_SECRET"
    azure-subscription-id: "$AZURE_SUBSCRIPTION_ID"
    azure-size: "$AZURE_INSTALL_VM_SIZE"
    azure-location: "$AZURE_LOCATION"
    azure-image: "Canonical:UbuntuServer:18.04-LTS:latest"
hosts:
  apps:
    size: 0
    dedicated: true
  core:
    driver:
      options:
        azure-open-port:
          - "80,8080"
components:
  install-dashboard: false
  tsuru-image: tsuru/api:$TSURUVERSION
  tsuru:
    config:
      kubernetes:
        provider:
          azurekubernetesservice:
            client-id: "$AZURE_CLIENT_ID"
            client-secret: "$AZURE_CLIENT_SECRET"
      debug: true
      iaas:
        dockermachine:
          debug: true
